language: node_js
node_js:
    - "0.10"
script: node_modules/karma/bin/karma start e2e/app.e2e.ts --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
